clear all; close all;
I1 = imread('assets/cafe_van_gogh.jpg');
I2 = imresize(I1, 0.5);
f1 = im2gray(I1);
f2 = im2gray(I2);
points1 = detectSIFTFeatures(f1);
points2 = detectSIFTFeatures(f2);
Nbest = 100;
bestFeatures1 = points1.selectStrongest(Nbest);
bestFeatures2 = points2.selectStrongest(Nbest);
figure(1); imshow(I1);
hold on;
plot(bestFeatures1);
title(sprintf('SIFT - Original (top 100 of %d)', points1.Count));
hold off;
figure(2); imshow(I2);
hold on;
plot(bestFeatures2);
title(sprintf('SIFT - Half size (top 100 of %d)', points2.Count));
hold off;